#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/chajmart/MPC/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: memory

depend: memory-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.memory $(@)

.PHONY: memory
memory:
	@$(MAKE) -f Makefile.memory all

.PHONY: memory-depend
memory-depend:
	@$(MAKE) -f Makefile.memory depend

project_name_list:
	@echo memory
